language: java
jdk:
  - openjdk6
install: mvn install -DskipTests=true -B
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
script: "mvn test -B"
after_script:
 - "sh -e /etc/init.d/xvfb stop"
